### ISSUE TITLE
How to break out of a turbo frame?

### ISSUE THREAD

**Issue by cspeer** [software-mansion-labs/react-native-turbo-demo#138]
Hi,

I'm trying to break out of a turbo frame. The turbo documentation states that I can just use `target="_top"`, but this results in opening the browser as if this was an external URL.

Thanks,
Chris

**Comment by pfeiffer** [comment]
This is expected behavior.

In Turbo, providing `target="_top"` navigates the `window` (ie. skips Turbo all-together).

You can use the [`onOpenExternalUrl`](https://github.com/software-mansion-labs/react-native-turbo-demo/blob/main/packages/turbo/README.md#onopenexternalurl) prop on the `VisitableView` to customize what happen when a non-Turbo navigation event happen (ie. perform an in-app navigation event with `navigateTo(..)`). The default is to open it in a browser, but you're free to handle it however you like :-)

**Comment by cspeer** [comment]
Oh, I didn't know `target="_top"` skips Turbo. I thought it targets not the `window` but the root navigation so to speak.
I'll go with `onOpenExternalUrl` then. Thanks so much!
